// /src/restaurantMessages.js

const restaurantMessages = {
    en: {
      milk: "I have a severe food allergy to milk. Please ensure that my meal is completely free of milk and all dairy products. Your careful preparation is crucial for my safety. Thank you! Please show this message to your server or manager to help ensure my food is prepared safely.",
      peanuts: "I have a severe food allergy to peanuts. Please make sure that my meal contains no peanuts or any peanut-derived ingredients. Your extra precautions are very important to me. Thank you! Please show this message to your server or manager to ensure my food is prepared safely.",
      eggs: "I have a food allergy to eggs. Please ensure that my dish is completely free of eggs or any egg-based products. I appreciate your attention to my dietary needs. Thank you! Please show this message to your server or manager to guarantee my food is prepared safely.",
      wheat: "I have a food allergy to wheat. Please prepare my food without any wheat or wheat-derived ingredients to keep it safe for me. I truly appreciate your help. Thank you! Please show this message to your server or manager to ensure my food is prepared safely.",
      fish: "I have a food allergy to fish. Please make sure that my meal is entirely free from fish and fish derivatives. Your care in preparing my meal is greatly appreciated. Thank you! Please show this message to your server or manager to ensure my food is prepared safely.",
      shellfish: "I have a food allergy to shellfish. Please ensure that my food is completely free of shellfish or any related products. Your attention to my safety is important to me. Thank you! Please show this message to your server or manager to ensure my food is prepared safely.",
      soy: "I have a food allergy to soy. Please prepare my meal without any soy or soy-based ingredients. I appreciate your efforts to accommodate my dietary restrictions. Thank you! Please show this message to your server or manager to ensure my food is prepared safely.",
      tree_nuts: "I have a food allergy to tree nuts. Please ensure that my food is completely free of tree nuts and any derivatives. Your careful preparation means a lot to me. Thank you! Please show this message to your server or manager to ensure my food is prepared safely.",
      sesame: "I have a food allergy to sesame. Please make sure that my meal contains no sesame or sesame-derived products. I rely on your attention to detail for my safety. Thank you! Please show this message to your server or manager to ensure my food is prepared safely."
    },
    es: {
      milk: "Tengo una alergia alimentaria severa a la leche. Por favor, asegúrese de que mi comida esté completamente libre de leche y productos lácteos. Su preparación cuidadosa es fundamental para mi seguridad. ¡Gracias! Por favor, muestre este mensaje a su mesero o gerente para garantizar que mi comida se prepare de forma segura.",
      peanuts: "Tengo una alergia alimentaria severa a los cacahuetes. Por favor, garantice que mi plato esté totalmente libre de cacahuetes y de cualquier derivado. Su atención extra es muy importante para mí. ¡Gracias! Por favor, muestre este mensaje a su mesero o gerente para asegurar que mi comida se prepare de forma segura.",
      eggs: "Tengo alergia a los huevos. Por favor, asegúrese de que mi plato esté completamente libre de huevos o productos derivados. Aprecio mucho su atención a mis necesidades dietéticas. ¡Gracias! Por favor, muestre este mensaje a su mesero o gerente para garantizar que mi comida se prepare de forma segura.",
      wheat: "Tengo alergia al trigo. Por favor, prepare mi comida sin trigo ni ingredientes derivados del trigo para que sea segura para mí. Agradezco sinceramente su ayuda. ¡Gracias! Por favor, muestre este mensaje a su mesero o gerente para asegurar que mi comida se prepare de forma segura.",
      fish: "Tengo alergia a los pescados. Por favor, asegúrese de que mi comida esté completamente libre de pescado y sus derivados. Su cuidado en la preparación es muy importante para mí. ¡Gracias! Por favor, muestre este mensaje a su mesero o gerente para garantizar que mi comida se prepare de forma segura.",
      shellfish: "Tengo alergia a los mariscos. Por favor, asegúrese de que mi plato esté completamente libre de mariscos o productos relacionados. Su atención a mi seguridad es fundamental. ¡Gracias! Por favor, muestre este mensaje a su mesero o gerente para asegurar que mi comida se prepare de forma segura.",
      soy: "Tengo alergia a la soja. Por favor, prepare mi comida sin soja ni productos derivados de la soja. Agradezco su consideración hacia mis restricciones dietéticas. ¡Gracias! Por favor, muestre este mensaje a su mesero o gerente para garantizar que mi comida se prepare de forma segura.",
      tree_nuts: "Tengo alergia a los frutos secos. Por favor, asegúrese de que mi comida esté totalmente libre de frutos secos y de sus derivados. Muchísimas gracias por su atención y cuidado. ¡Por favor, muestre este mensaje a su mesero o gerente para asegurar que mi comida se prepare de forma segura!",
      sesame: "Tengo alergia al sésamo. Por favor, asegúrese de que mi comida no contenga sésamo ni productos derivados. Agradezco mucho su ayuda para mantenerme seguro. ¡Gracias! Por favor, muestre este mensaje a su mesero o gerente para garantizar que mi comida se prepare de forma segura."
    },
    fr: {
      milk: "J'ai une allergie alimentaire sévère au lait. Veuillez vous assurer que mon repas soit entièrement exempt de lait et de produits laitiers. Votre préparation minutieuse est essentielle pour ma sécurité. Merci ! Veuillez montrer ce message à votre serveur ou responsable afin de garantir que ma nourriture soit préparée en toute sécurité.",
      peanuts: "J'ai une allergie alimentaire sévère aux arachides. Veuillez vous assurer que mon plat ne contient aucune arachide ni dérivé. Votre vigilance est grandement appréciée. Merci ! Veuillez montrer ce message à votre serveur ou responsable afin de garantir que ma nourriture soit préparée en toute sécurité.",
      eggs: "J'ai une allergie aux œufs. Veuillez préparer mon repas sans œufs ni produits à base d'œufs. Merci de respecter mes besoins alimentaires. Veuillez montrer ce message à votre serveur ou responsable afin de garantir que ma nourriture soit préparée en toute sécurité.",
      wheat: "J'ai une allergie au blé. Veuillez préparer ma nourriture sans blé ni ingrédients dérivés du blé. Je vous remercie de prendre soin de ma sécurité. Veuillez montrer ce message à votre serveur ou responsable afin de garantir que ma nourriture soit préparée en toute sécurité.",
      fish: "J'ai une allergie aux poissons. Veuillez vous assurer que mon repas est totalement exempt de poissons et de leurs dérivés. Merci de prendre soin de ma santé. Veuillez montrer ce message à votre serveur ou responsable afin de garantir que ma nourriture soit préparée en toute sécurité.",
      shellfish: "J'ai une allergie aux fruits de mer. Veuillez vous assurer que mon plat ne contient aucun fruit de mer ni produit connexe. Merci de votre compréhension. Veuillez montrer ce message à votre serveur ou responsable afin de garantir que ma nourriture soit préparée en toute sécurité.",
      soy: "J'ai une allergie au soja. Veuillez préparer mon repas sans soja ni produits dérivés du soja. Merci de prendre en compte mes restrictions alimentaires. Veuillez montrer ce message à votre serveur ou responsable afin de garantir que ma nourriture soit préparée en toute sécurité.",
      tree_nuts: "J'ai une allergie aux fruits à coque. Veuillez vous assurer que mon repas est complètement exempt de fruits à coque et de leurs dérivés. Merci de votre attention. Veuillez montrer ce message à votre serveur ou responsable afin de garantir que ma nourriture soit préparée en toute sécurité.",
      sesame: "J'ai une allergie au sésame. Veuillez préparer mon repas sans sésame ni produits dérivés du sésame. Merci de prendre soin de ma sécurité. Veuillez montrer ce message à votre serveur ou responsable afin de garantir que ma nourriture soit préparée en toute sécurité."
    }
  };
  
  export default restaurantMessages;
  